[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Role = ["member"] }

[[redirects]]
  from = "/*"
  to = "/login"
  status = 302
